language: generic

sudo: required

script:
    - git clone https://github.com/uqbar-project/wollok-cli
    - export PATH="$PATH:./wollok-cli"
    - wollok check example.wlk
    - wollok check list.wtest
    - wollok check set.wtest
