language: generic

sudo: required

script:
    - git clone https://github.com/uqbar-project/wollok-cli
    - export PATH="$PATH:./wollok-cli"
    - wollok check src/example.wlk
    - wollok check src/list.wtest
    - wollok check src/set.wtest
